# Imagen base de Python
FROM python:3.12-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir cryptography



COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Exponer el puerto Flask
EXPOSE 5000

# Comando para ejecutar la app con gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
